use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenType {
    Int(i64),
    Float(f64),
    String(String),
    Boolean(bool),
    Identifier(String),

    Async,
    Await,
    Cell,
    Say,
    Shout,
    Emit,
    When,
    Else,
    While,
    Each,
    In,
    Pick,
    Dare,
    Catch,
    Load,
    Shape,
    Style,
    Class,
    As,
    None,
    Break,
    Continue,
    Do,
    Yield,
    Macro,
    Pub,
    Super,

    TypeInt,
    TypeFloat,
    TypeString,
    TypeBool,
    TypeList,
    TypeDict,
    TypeSelf,
    #[allow(dead_code)]
    TypeFn,
    #[allow(dead_code)]
    TypeNil,

    Trait,
    Impl,
    For,
    Extends,
    Throw,

    Question,
    Tilde,
    Backslash,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    Equal,
    EqualEqual,
    Bang,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    AndAnd,
    OrOr,
    Pipe,
    Ampersand,
    Caret,
    ShiftLeft,
    ShiftRight,
    Dot,
    DotDot,
    DotDotDot,
    Arrow,
    FatArrow,
    PipeArrow,

    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Colon,
    Semicolon,

    StringPart(String),
    ExprString(String),
    StringEnd,

    Indent,
    Dedent,
    Newline,
    Eof,
    Illegal(String),
}

#[derive(Debug, Clone)]
pub struct Token {
    pub token_type: TokenType,
    pub line: usize,
    pub col: usize,
}

impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenType::Int(n) => write!(f, "{}", n),
            TokenType::Float(n) => write!(f, "{}", n),
            TokenType::String(s) => write!(f, "\"{}\"", s),
            TokenType::Boolean(b) => write!(f, "{}", b),
            TokenType::Identifier(s) => write!(f, "{}", s),
            TokenType::Async => write!(f, "async"),
            TokenType::Await => write!(f, "await"),
            TokenType::Cell => write!(f, "cell"),
            TokenType::Say => write!(f, "say"),
            TokenType::Shout => write!(f, "shout"),
            TokenType::Emit => write!(f, "emit"),
            TokenType::When => write!(f, "when"),
            TokenType::Else => write!(f, "else"),
            TokenType::While => write!(f, "while"),
            TokenType::Each => write!(f, "over"),
            TokenType::In => write!(f, "in"),
            TokenType::Pick => write!(f, "pick"),
            TokenType::Dare => write!(f, "dare"),
            TokenType::Catch => write!(f, "catch"),
            TokenType::Load => write!(f, "load"),
            TokenType::Shape => write!(f, "shape"),
            TokenType::Style => write!(f, "style"),
            TokenType::Class => write!(f, "class"),
            TokenType::As => write!(f, "as"),
            TokenType::None => write!(f, "none"),
            TokenType::Break => write!(f, "break"),
            TokenType::Continue => write!(f, "continue"),
            TokenType::Do => write!(f, "do"),
            TokenType::Yield => write!(f, "yield"),
            TokenType::Macro => write!(f, "macro"),
            TokenType::Pub => write!(f, "pub"),
            TokenType::Super => write!(f, "super"),
            TokenType::TypeInt => write!(f, "int"),
            TokenType::TypeFloat => write!(f, "float"),
            TokenType::TypeString => write!(f, "string"),
            TokenType::TypeBool => write!(f, "bool"),
            TokenType::TypeList => write!(f, "list"),
            TokenType::TypeDict => write!(f, "dict"),
            TokenType::TypeFn => write!(f, "fn"),
            TokenType::TypeNil => write!(f, "none"),
            TokenType::TypeSelf => write!(f, "Self"),
            TokenType::Trait => write!(f, "trait"),
            TokenType::Impl => write!(f, "impl"),
            TokenType::For => write!(f, "for"),
            TokenType::Extends => write!(f, "extends"),
            TokenType::Throw => write!(f, "throw"),
            TokenType::Question => write!(f, "?"),
            TokenType::Tilde => write!(f, "~"),
            TokenType::Backslash => write!(f, "\\"),
            TokenType::Plus => write!(f, "+"),
            TokenType::Minus => write!(f, "-"),
            TokenType::Star => write!(f, "*"),
            TokenType::Slash => write!(f, "/"),
            TokenType::Percent => write!(f, "%"),
            TokenType::PlusEqual => write!(f, "+="),
            TokenType::MinusEqual => write!(f, "-="),
            TokenType::StarEqual => write!(f, "*="),
            TokenType::SlashEqual => write!(f, "/="),
            TokenType::PercentEqual => write!(f, "%="),
            TokenType::Equal => write!(f, "="),
            TokenType::EqualEqual => write!(f, "=="),
            TokenType::Bang => write!(f, "!"),
            TokenType::BangEqual => write!(f, "!="),
            TokenType::Less => write!(f, "<"),
            TokenType::LessEqual => write!(f, "<="),
            TokenType::Greater => write!(f, ">"),
            TokenType::GreaterEqual => write!(f, ">="),
            TokenType::AndAnd => write!(f, "&&"),
            TokenType::OrOr => write!(f, "||"),
            TokenType::Pipe => write!(f, "|"),
            TokenType::Ampersand => write!(f, "&"),
            TokenType::Caret => write!(f, "^"),
            TokenType::ShiftLeft => write!(f, "<<"),
            TokenType::ShiftRight => write!(f, ">>"),
            TokenType::Dot => write!(f, "."),
            TokenType::DotDot => write!(f, ".."),
            TokenType::DotDotDot => write!(f, "..."),
            TokenType::Arrow => write!(f, "->"),
            TokenType::FatArrow => write!(f, "=>"),
            TokenType::PipeArrow => write!(f, "|>"),
            TokenType::LParen => write!(f, "("),
            TokenType::RParen => write!(f, ")"),
            TokenType::LBrace => write!(f, "{{"),
            TokenType::RBrace => write!(f, "}}"),
            TokenType::LBracket => write!(f, "["),
            TokenType::RBracket => write!(f, "]"),
            TokenType::Comma => write!(f, ","),
            TokenType::Colon => write!(f, ":"),
            TokenType::Semicolon => write!(f, ";"),
            TokenType::StringPart(s) => write!(f, "StringPart({})", s),
            TokenType::ExprString(s) => write!(f, "ExprString({})", s),
            TokenType::StringEnd => write!(f, "StringEnd"),
            TokenType::Indent => write!(f, "INDENT"),
            TokenType::Dedent => write!(f, "DEDENT"),
            TokenType::Newline => write!(f, "NEWLINE"),
            TokenType::Eof => write!(f, "EOF"),
            TokenType::Illegal(s) => write!(f, "Illegal({})", s),
        }
    }
}

impl Token {
    #[allow(dead_code)]
    pub fn new(token_type: TokenType, line: usize) -> Self {
        Token {
            token_type,
            line,
            col: 0,
        }
    }

    pub fn new_col(token_type: TokenType, line: usize, col: usize) -> Self {
        Token {
            token_type,
            line,
            col,
        }
    }
}
